/**
 * Tailwind config — tokens portados directamente del design system "Cyber-Fiducia".
 * Fuente: los archivos DESIGN.md y code.html de stitch_nextgen_finance_portal.
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#00696f',
        'on-secondary-container': '#556d00',
        'primary-fixed': '#74f5ff',
        'surface-variant': '#303444',
        'surface-container-lowest': '#090e1c',
        'primary-fixed-dim': '#00dbe7',
        error: '#ffb4ab',
        'surface-dim': '#0e1321',
        'surface-tint': '#00dbe7',
        'primary-container': '#00f2ff',
        'on-background': '#dee2f6',
        'on-surface': '#dee2f6',
        surface: '#0e1321',
        'outline-variant': '#3a494b',
        'inverse-on-surface': '#2b303f',
        'surface-container': '#1a1f2e',
        'secondary-container': '#c3f400',
        'surface-container-highest': '#303444',
        'on-tertiary-fixed': '#410003',
        'tertiary-fixed-dim': '#ffb3ac',
        'error-container': '#93000a',
        'tertiary-container': '#ffd0cb',
        background: '#0e1321',
        outline: '#849495',
        'surface-container-low': '#161b2a',
        'surface-bright': '#343948',
        'on-tertiary-container': '#c20018',
        secondary: '#ffffff',
        'secondary-fixed': '#c3f400',
        'on-tertiary-fixed-variant': '#930010',
        'on-secondary-fixed-variant': '#3c4d00',
        'on-error': '#690005',
        'on-primary-container': '#006a71',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#002022',
        'surface-container-high': '#252a39',
        'on-surface-variant': '#b9cacb',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed-dim': '#abd600',
        'on-secondary-fixed': '#161e00',
        tertiary: '#fff5f4',
        'on-tertiary': '#680008',
        'on-secondary': '#283500',
        'on-primary': '#00363a',
        'tertiary-fixed': '#ffdad6',
        'inverse-surface': '#dee2f6',
        primary: '#e1fdff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'margin-desktop': '40px',
        gutter: '24px',
        unit: '4px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'display-lg': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'headline-lg': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'data-mono': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        'label-caps': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      keyframes: {
        scan: {
          '0%': { top: '0%', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { top: '100%', opacity: '0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.02)' },
        },
      },
      animation: {
        scan: 'scan 3s linear infinite',
        'pulse-soft': 'pulse-soft 2s cubic-bezier(0.4,0,0.6,1) infinite',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
